setwd("C:/Users/gaguilarc/Downloads")
install.packages("tidyverse_1.3.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("broom_1.0.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("dplyr_1.0.10.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rlang_1.0.6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("vctrs_0.5.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("R6_2.5.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("generics_0.1.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("glue_1.6.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("lifecycle_1.0.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("magrittr_2.0.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("pillar_1.8.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("cli_3.4.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("fansi_1.0.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("utf8_1.2.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tibble_3.1.8.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("pkgconfig_2.0.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tidyselect_1.2.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("purrr_0.3.5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tidyr_1.2.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("backports_1.4.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("dbplyr_2.2.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("DBI_1.1.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("assertthat_0.2.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("forcats_0.5.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("ggplot2_3.3.6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("gtable_0.3.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("scales_1.2.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("munsell_0.5.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("colorspace_2.0-3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("googledrive_2.0.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("gargle_1.2.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("fs_1.5.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("googlesheets4_1.0.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("cellranger_1.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("haven_2.5.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("hms_1.1.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("ellipsis_0.3.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("httr_1.4.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("jsonlite_1.8.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("lubridate_1.8.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("modelr_0.1.9.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("readr_2.1.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tzdb_0.3.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("readxl_1.4.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("reprex_2.0.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("withr_2.5.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rvest_1.0.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("xml2_1.3.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("stringr_1.4.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("stringi_1.7.8.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("crayon_1.5.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(tidyverse)
library(dplyr)
library(zoo)

#FOR GT
install.packages("gt_0.7.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("htmltools_0.5.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("digest_0.6.30.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("fastmap_1.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("sass_0.4.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(gt)
df %>% gt() %>% 
  opt_stylize()


library(readxl)
read_excel("ejemplo.xlsx")
install.packages("rJava_1.0-6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
library(writexl)
install.packages("writexl_1.4.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
library(tseries)
install.packages("tseries_0.10-52.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("quadprog_1.5-8.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("zoo_1.8-11.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("quantmod_0.4.20.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("xts_0.12.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("TTR_0.24.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("curl_4.3.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(data.table)
install.packages("data.table_1.14.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("bit64_4.0.5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(ggplot2)
install.packages("labeling_0.4.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("farver_2.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

install.packages("xlsx_0.6.5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
library(rmarkdown)
install.packages("rmarkdown_2.18.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("knitr_1.40.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("xfun_0.34.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("evaluate_0.18.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("yaml_2.3.6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("markdown_1.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("base64enc_0.1-3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("highr_0.9.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("mime_0.12.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tinytex_0.42.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(kableExtra)
install.packages("kableExtra_1.3.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rstudioapi_0.14.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("svglite_2.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("systemfonts_1.0.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("viridisLite_0.4.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("webshot_0.5.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(MASS)
install.packages("MASS_7.3-58.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(janitor)
install.packages("janitor_2.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("snakecase_0.11.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(expm)
install.packages("expm_0.999-6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(XLConnect)
install.packages("XLConnect_1.0.6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
require(XLConnect)

library(readr)
install.packages("vroom_1.6.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("bit_4.0.5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(xlsx)
install.packages("xlsxjars_0.6.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

install.packages("jquerylib_0.1.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(ggrepel) #To put labels and avoid stacking
install.packages("ggrepel_0.9.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(fitdistrplus)
install.packages("fitdistrplus_1.1-8.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(sqldf)
install.packages("sqldf_0.4-11.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("gsubfn_0.7.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("proto_1.0.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("RSQLite_2.2.20.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("RSQL_0.2.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("blob_1.2.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("chron_2.3-59.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(RODBC) #To connect to ODBC
install.packages("RODBC_1.3-20.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(pracma) #To extend expm and get nrooth of matrices
install.packages("pracma_2.4.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(reticulate) #To read python code in quarto/markdown
install.packages("reticulate_1.28.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(doconv) #to convert word to pdf
install.packages("doconv_0.3.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("magick_2.7.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("locatexec_0.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("pdftools_3.3.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("qpdf_1.3.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(fastDummies) #for Creating Dummies from categorical variables
install.packages("fastDummies_1.6.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
library(e1071) # for NaiveBayes
install.packages("e1071_1.7-13.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("proxy_0.4-27.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(factoextra)
install.packages("factoextra_1.0.7.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("ggpubr_0.6.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("ggsignif_0.6.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rstatix_0.7.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("car_3.1-1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("carData_3.0-5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("abind_1.4-5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tidyr_1.3.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(rappdirs)
install.packages("rappdirs_0.3.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(dplyr)
install.packages("dplyr_1.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rlang_1.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("vctrs_0.6.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tibble_3.2.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("purrr_1.0.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
remove.packages("tidyr")

library(ReDaMoR)
install.packages("ReDaMoR_0.7.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("visNetwork_2.1.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rintrojs_0.3.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("DT_0.28.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("colourpicker_1.2.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("miniUI_0.1.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("shinyjs_2.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("igraph_1.5.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(tidymodels)
install.packages("tidymodels_1.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
remove.packages("broom")
install.packages("broom_1.0.5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
remove.packages("cli")
install.packages("cli_3.6.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("conflicted_1.2.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("dials_1.2.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("hardhat_1.3.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("infer_1.0.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("modeldata_1.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("parsnip_1.1.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("tune_1.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("workflows_1.1.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("workflowsets_1.0.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("yardstick_1.2.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("DiceDesign_1.9.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
remove.packages("dplyr")
install.packages("dplyr_1.1.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
remove.packages("pillar")
install.packages("pillar_1.9.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
remove.packages("ggplot2")
install.packages("ggplot2_3.4.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
remove.packages("recipes")
install.packages("recipes_1.0.6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("GPfit_1.0-8.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("lhs_1.1.6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("modelenv_0.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(caret)
install.packages("caret_6.0-94.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("ModelMetrics_1.2.2.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("pROC_1.18.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("randomForest_4.7-1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
library(gbm)
install.packages("gbm_2.1.8.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
library(kernlab) #for SVM model
install.packages("kernlab_0.9-32.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(rstanarm)
install.packages("rstanarm_2.21.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("bayesplot_1.10.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rstantools_2.3.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("RcppParallel_5.1.7.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("shinystan_2.6.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("dygraphs_1.1.1.6.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("threejs_0.3.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("gtools_3.9.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("shinythemes_1.2.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("lme4_1.1-34.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("minqa_1.2.5.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("nloptr_2.0.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("gtools_3.9.4.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("loo_2.6.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("matrixStats_1.0.0.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("rstan_2.21.8.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("inline_0.3.19.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("pkgbuild_1.4.2.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("callr_3.7.3.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("prettyunits_1.1.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)
install.packages("StanHeaders_2.26.27.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

library(arrow)
install.packages("arrow_13.0.0.1.zip",lib="C:/Users/gaguilarc/AppData/Local/Programs/R/R-4.2.1/library",repos=NULL)

#CONFLICTS
# dplyr has conflicts with filter() y lag()
# dplyr::filter()
# dplyr::lag()
# lubridate::as.difftime() masks base::as.difftime()
# data.table::between()    masks dplyr::between()
# lubridate::date()        masks base::date()
# dplyr::filter()          masks stats::filter()
# data.table::first()      masks dplyr::first()
# data.table::hour()       masks lubridate::hour()
# lubridate::intersect()   masks base::intersect()
# data.table::isoweek()    masks lubridate::isoweek()
# dplyr::lag()             masks stats::lag()
# data.table::last()       masks dplyr::last()
# data.table::mday()       masks lubridate::mday()
# data.table::minute()     masks lubridate::minute()
# data.table::month()      masks lubridate::month()
# data.table::quarter()    masks lubridate::quarter()
# data.table::second()     masks lubridate::second()
# lubridate::setdiff()     masks base::setdiff()
# purrr::transpose()       masks data.table::transpose()
# lubridate::union()       masks base::union()
# data.table::wday()       masks lubridate::wday()
# data.table::week()       masks lubridate::week()
# data.table::yday()       masks lubridate::yday()
# data.table::year()       masks lubridate::year()


# ____________________
# Sucursal
# FechaPago
# CapitalPagado
# InteresPagado
# TipoCuota
# ModuloTrx
# Usuario
# HoraPago